# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm install playwright
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get upgrade -y
        sudo apt-get install -y mosquitto
    - name: Setup envitonment
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        playwright install
        xvfb-run npx playwright test
        npm install node-red@3.0.2
        ./node_modules/node-red/bin/node-red-pi &
        sleep 3
